#!/usr/bin/env python3
"""
scripts/deployment_status.py — deployment claims, derived (HOD-715).

`make deployment-status`          renders the table
`make deployment-status --check`  validates the file's own rules

WHY THIS EXISTS. The README told a reader that asymmetric signing "has not
been built" for a commit after it was built, and that a capability was
executed in one paragraph while another paragraph called it designed-only.
An external review found both. Prose that says whether infrastructure is
deployed is a claim like any other, and this project's rule is that a claim
must be derived from its evidence rather than remembered — so the
executed/not-executed state now lives in docs/deployment_status.json, this
script renders and validates it, and `make check-docs` fails the build when
the documents disagree with it.

The validation rules are the honest part:
  * "verified" REQUIRES both an evidence_source and a last_verified_utc.
    A capability nobody checked cannot be described as working.
  * "scripted_not_executed" REQUIRES last_verified_utc to be null. If it was
    verified, it was executed, and the status is wrong.
  * every status must come from the file's own vocabulary.
"""

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
STATUS_PATH = ROOT / "docs" / "deployment_status.json"

SYMBOL = {
    "verified": "✓ verified",
    "provisioned_unverified": "~ provisioned, unverified",
    "scripted_not_executed": "○ scripted, never run",
    "in_process_only": "▣ in-process only",
}


def load() -> dict:
    return json.loads(STATUS_PATH.read_text())


def validate(doc: dict) -> list:
    """Returns a list of failures; empty means the file is internally honest."""
    failures = []
    vocabulary = set(doc.get("status_vocabulary", {}))
    if not vocabulary:
        failures.append("status_vocabulary is missing — statuses would be undefined terms.")
    for name, cap in doc.get("capabilities", {}).items():
        status = cap.get("status")
        if status not in vocabulary:
            failures.append(f"{name}: status {status!r} is not in status_vocabulary")
            continue
        if status == "verified":
            if not cap.get("evidence_source"):
                failures.append(f"{name}: 'verified' without an evidence_source — "
                                "a capability nobody checked cannot be reported as working")
            if not cap.get("last_verified_utc"):
                failures.append(f"{name}: 'verified' without a last_verified_utc — "
                                "verification with no date is not verification")
        if status == "scripted_not_executed" and cap.get("last_verified_utc"):
            failures.append(f"{name}: 'scripted_not_executed' but carries "
                            f"last_verified_utc={cap['last_verified_utc']!r} — if it was "
                            "verified it was executed, so the status is wrong")
        if not cap.get("detail"):
            failures.append(f"{name}: no detail — a status with no explanation is not a claim")
    return failures


def render(doc: dict) -> str:
    """The markdown table the docs embed. Generated, never hand-edited."""
    lines = [
        "<!-- GENERATED by scripts/deployment_status.py from docs/deployment_status.json.",
        "     Do not hand-edit: `make check-docs` compares the docs against that file. -->",
        "",
        "| Capability | State | Evidence | Last verified (UTC) |",
        "|---|---|---|---|",
    ]
    for name, cap in doc["capabilities"].items():
        verified = cap.get("last_verified_utc") or "—"
        evidence = cap.get("evidence_source") or "—"
        lines.append(f"| `{name}` | {SYMBOL.get(cap['status'], cap['status'])} | {evidence} | {verified} |")
    lines.append("")
    lines.append("`○ scripted, never run` means exactly that: the script is in this repository and "
                 "reproducible, and it has not been executed against the live project. "
                 "`▣ in-process only` means the boundary is enforced by application code inside one "
                 "Cloud Run process — real and tested, but not a cloud-infrastructure boundary.")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description="Render or validate the deployment status table.")
    ap.add_argument("--check", action="store_true", help="validate only; exit 1 on any failure")
    args = ap.parse_args()

    doc = load()
    failures = validate(doc)
    if failures:
        print("DEPLOYMENT STATUS INVALID:", file=sys.stderr)
        for f in failures:
            print(f"  - {f}", file=sys.stderr)
        return 1

    if args.check:
        counts = {}
        for cap in doc["capabilities"].values():
            counts[cap["status"]] = counts.get(cap["status"], 0) + 1
        print("Deployment status VALID: " + ", ".join(
            f"{n} {s}" for s, n in sorted(counts.items())))
        return 0

    print(render(doc))
    return 0


if __name__ == "__main__":
    sys.exit(main())
