import re
from typing import List

from src.evidence.semantic_backstop import SemanticBackstop

class OverclaimLintViolation(Exception):
    """Raised when generated text or render payload violates the overclaim honesty invariant."""
    pass

class OverclaimLint:
    """
    Render-Time Overclaim Lint (HOD-320 / Invariants 1 & 2).
    Rejects any text that asserts model training, training-set membership,
    or model ingestion proof.
    """

    FORBIDDEN_PHRASES = [
        r"trained\s+on",
        r"was\s+in\s+the\s+training\s+set",
        r"proves?\s+training",
        r"proves?\s+the\s+model\s+saw",
        r"your\s+(art|work|content|essay|repo|music)\s+is\s+inside",
        r"proves?\s+ingestion",
        r"in\s+(the|a)\s+training\s+dataset",
        r"model\s+has\s+memorized",
        r"proves?\s+membership"
    ]

    def __init__(self, backstop: SemanticBackstop = None):
        # Injectable so a test can supply a stub; defaults to the real backstop,
        # which disables itself when no vector is available.
        self._backstop = backstop if backstop is not None else SemanticBackstop()

    def lint_text(self, text: str) -> str:
        """
        Lints text for overclaim violations.
        Raises OverclaimLintViolation if any forbidden phrase or paraphrase is detected.
        Returns the original text clean if no violation found.
        """
        text_lower = text.lower()
        for pattern in self.FORBIDDEN_PHRASES:
            match = re.search(pattern, text_lower)
            if match:
                raise OverclaimLintViolation(
                    f"Honesty Invariant Violation: Generated text contains overclaim assertion "
                    f"matching forbidden pattern '{pattern}': '{match.group(0)}' in text: '{text}'"
                )

        # SEMANTIC BACKSTOP — strictness only. The regex list above rejects 4 of
        # 12 known paraphrases (measured, published, regenerated by
        # `make lint-coverage`), so a claim phrased around the patterns passes.
        # This can only ADD a refusal: it runs after every regex has already
        # declined to reject, so no input reaches it that the regexes would have
        # blocked, and there is no path by which it permits text. If the model
        # is unreachable or offline-uncached it returns None and the regex
        # verdict stands, exactly as before it existed.
        anchor = self._backstop.is_semantic_overclaim(text)
        if anchor:
            raise OverclaimLintViolation(
                f"Honesty Invariant Violation: Generated text is a semantic paraphrase of a "
                f"forbidden claim (nearest anchor: '{anchor}') though it matched no literal "
                f"pattern, in text: '{text}'"
            )
        return text
